from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .planner import PlanEntry


class CMakeDependencyIndex:
    file_name = "BAASDependencyIndex.cmake"

    def path_for(self, ctx) -> Path:  # noqa: ANN001
        cmake_manifest = getattr(ctx, "cmake_manifest", "")
        if cmake_manifest:
            return Path(cmake_manifest).resolve()
        return ctx.workspace_root / "cmake" / self.file_name

    def remove(self, ctx) -> None:  # noqa: ANN001
        path = self.path_for(ctx)
        if path.exists():
            path.unlink()

    def write(self, ctx, entries: Iterable[PlanEntry]) -> Path:  # noqa: ANN001
        path = self.path_for(ctx)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_suffix(path.suffix + ".tmp")
        tmp_path.write_text(self.render(ctx, entries), encoding="utf-8")
        tmp_path.replace(path)
        return path

    def render(self, ctx, entries: Iterable[PlanEntry]) -> str:  # noqa: ANN001
        lines = [
            "# Generated by python -m deploy.bootstrap_dependency",
            "# Do not edit by hand.",
            "",
            f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_ROOT [[{self.cmake_value(ctx.deps_root)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_ASSETS_ROOT [[{self.cmake_value(ctx.assets_root)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_PLATFORM_KEY [[{self.cmake_value(ctx.platform_key)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_ARCH_KEY [[{self.cmake_value(ctx.arch_key)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_COMPILER_KEY [[{self.cmake_value(ctx.compiler_id)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_BUILD_TYPE_KEY [[{self.cmake_value(ctx.config)}]])",
            f"set_property(GLOBAL PROPERTY BAAS_VARIANT [[{self.cmake_value(ctx.variant)}]])",
            "",
        ]

        dependencies = sorted((entry for entry in entries if entry.kind == "dependency"), key=lambda item: item.name)
        dependency_names = [entry.name for entry in dependencies]
        lines.append(f"set_property(GLOBAL PROPERTY BAAS_BOOTSTRAPPED_DEPENDENCIES [[{';'.join(dependency_names)}]])")
        lines.append("")
        for entry in dependencies:
            dependency_id = entry.name
            ready = entry.status == "cache_hit"
            lines.extend(
                [
                    f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_{dependency_id}_VERSION [[{self.cmake_value(entry.version)}]])",
                    f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_{dependency_id}_PROVIDER [[{self.cmake_value(entry.provider)}]])",
                    f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_{dependency_id}_READY {'TRUE' if ready else 'FALSE'})",
                    f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_{dependency_id}_CONFIG [[{self.cmake_value(ctx.config)}]])",
                ]
            )
            if ready:
                lines.append(f"set_property(GLOBAL PROPERTY BAAS_DEPENDENCY_{dependency_id}_PACKAGE_DIR [[{self.cmake_value(entry.package)}]])")
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def cmake_value(self, value) -> str:  # noqa: ANN001
        text = str(value)
        text = text.replace("\\", "/")
        text = text.replace("]]", "] ]")
        return text
