from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from .planner import PlanEntry


class CMakeDependencyIndex:
    file_name = "BAASDependencyIndex.cmake"

    def path_for(self, ctx) -> Path:  # noqa: ANN001
        return ctx.local_root / "cmake" / self.file_name

    def remove(self, ctx) -> None:  # noqa: ANN001
        path = self.path_for(ctx)
        if path.exists():
            path.unlink()

    def write(self, ctx, entries: Iterable[PlanEntry]) -> Path:  # noqa: ANN001
        path = self.path_for(ctx)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_suffix(path.suffix + ".tmp")
        tmp_path.write_text(self.render(ctx, entries), encoding="utf-8")
        tmp_path.replace(path)
        return path

    def render(self, ctx, entries: Iterable[PlanEntry]) -> str:  # noqa: ANN001
        lines = [
            "# Generated by python -m deploy.bootstrap_dependency",
            "# Do not edit by hand.",
            "",
            f'set(BAAS_DEPENDENCY_ROOT "{self.cmake_value(ctx.deps_root)}")',
            f'set(BAAS_ASSETS_ROOT "{self.cmake_value(ctx.assets_root)}")',
            f'set(BAAS_PLATFORM_KEY "{self.cmake_value(ctx.platform_key)}")',
            f'set(BAAS_ARCH_KEY "{self.cmake_value(ctx.arch_key)}")',
            f'set(BAAS_COMPILER_KEY "{self.cmake_value(ctx.compiler_id)}")',
            f'set(BAAS_BUILD_TYPE_KEY "{self.cmake_value(ctx.config)}")',
            f'set(BAAS_VARIANT "{self.cmake_value(ctx.variant)}")',
            "",
        ]

        dependencies = sorted((entry for entry in entries if entry.kind == "dependency"), key=lambda item: item.name)
        for entry in dependencies:
            key = self.dependency_key(entry.name)
            ready = entry.status == "cache_hit"
            lines.extend(
                [
                    f'set(BAAS_DEP_{key}_VERSION "{self.cmake_value(entry.version)}")',
                    f'set(BAAS_DEP_{key}_PROVIDER "{self.cmake_value(entry.provider)}")',
                    f"set(BAAS_DEP_{key}_READY {'TRUE' if ready else 'FALSE'})",
                ]
            )
            if ready:
                lines.append(f'set(BAAS_DEP_{key}_PACKAGE_DIR "{self.cmake_value(entry.package)}")')
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def dependency_key(self, name: str) -> str:
        return re.sub(r"[^A-Za-z0-9]", "_", name).upper()

    def cmake_value(self, value) -> str:  # noqa: ANN001
        text = str(value)
        text = text.replace("\\", "/")
        text = text.replace('"', '\\"')
        return text
