set(BAAS_OCR_SERVER_VERSION_MAJOR 1)
set(BAAS_OCR_SERVER_VERSION_MINOR 2)
set(BAAS_OCR_SERVER_VERSION_PATCH 1)

set(BAAS_OCR_SERVER_VERSION "${BAAS_OCR_SERVER_VERSION_MAJOR}.${BAAS_OCR_SERVER_VERSION_MINOR}.${BAAS_OCR_SERVER_VERSION_PATCH}")