include_guard(GLOBAL)

function(baas_try_enable_cuda out_var)
    if(TARGET BAAS::CUDAHeaders AND TARGET BAAS::CUDA)
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    get_property(_ready GLOBAL PROPERTY BAAS_DEPENDENCY_cuda_READY)
    if(NOT _ready)
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    get_property(_cuda_version GLOBAL PROPERTY BAAS_DEPENDENCY_cuda_VERSION)
    if(NOT _cuda_version)
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    find_package(CUDAToolkit ${_cuda_version} QUIET)
    if(NOT CUDAToolkit_FOUND)
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    if(NOT TARGET BAAS::CUDAHeaders)
        add_library(BAAS::CUDAHeaders INTERFACE IMPORTED GLOBAL)
        set_target_properties(BAAS::CUDAHeaders PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CUDAToolkit_INCLUDE_DIRS}")
    endif()

    if(NOT TARGET BAAS::CUDA)
        add_library(BAAS::CUDA INTERFACE IMPORTED GLOBAL)
        set_target_properties(BAAS::CUDA PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CUDAToolkit_INCLUDE_DIRS}")
        if(TARGET CUDA::cudart)
            target_link_libraries(BAAS::CUDA INTERFACE CUDA::cudart)
        elseif(TARGET CUDA::cudart_static)
            target_link_libraries(BAAS::CUDA INTERFACE CUDA::cudart_static)
        endif()
    endif()

    set(${out_var} TRUE PARENT_SCOPE)
endfunction()

function(baas_require_cuda_target)
    get_property(_ready GLOBAL PROPERTY BAAS_DEPENDENCY_cuda_READY)
    if(NOT _ready)
        message(FATAL_ERROR "Dependency 'cuda' is not ready in BAAS dependency manifest: ${BAAS_DEPENDENCY_INDEX}")
    endif()

    baas_try_enable_cuda(_cuda_available)
    if(NOT _cuda_available)
        get_property(_cuda_version GLOBAL PROPERTY BAAS_DEPENDENCY_cuda_VERSION)
        if(_cuda_version)
            message(FATAL_ERROR "BAAS::CUDA requires CUDA Toolkit ${_cuda_version} or newer. Run python -m deploy.bootstrap_dependency --dependency cuda --build-type ${BAAS_DEPENDENCY_BUILD_TYPE}, then make sure CMake can find CUDAToolkit.")
        else()
            message(FATAL_ERROR "BAAS::CUDA requires a ready locked CUDA dependency. Run python -m deploy.bootstrap_dependency --dependency cuda --build-type ${BAAS_DEPENDENCY_BUILD_TYPE}.")
        endif()
    endif()
endfunction()
