include_guard(GLOBAL)

set(BAAS_WORKSPACE_ROOT "${CMAKE_SOURCE_DIR}/.baas" CACHE PATH "BAAS dependency bootstrap workspace")
if(DEFINED CMAKE_BUILD_TYPE AND NOT CMAKE_BUILD_TYPE STREQUAL "")
    set(BAAS_DEPENDENCY_BUILD_TYPE "${CMAKE_BUILD_TYPE}")
else()
    set(BAAS_DEPENDENCY_BUILD_TYPE "Release")
endif()

set(BAAS_DEPENDENCY_INDEX "${CMAKE_BINARY_DIR}/baas-dependency.cmake")

function(baas_find_first_glob out_var)
    set(_found "")
    foreach(_pattern IN LISTS ARGN)
        if(_pattern STREQUAL "")
            continue()
        endif()

        if(EXISTS "${_pattern}")
            set(_found "${_pattern}")
            break()
        endif()

        if(_pattern MATCHES "[*?[]")
            string(FIND "${_pattern}" "/**/" _recursive_sep)
            if(_recursive_sep GREATER_EQUAL 0)
                string(SUBSTRING "${_pattern}" 0 ${_recursive_sep} _recursive_root)
                math(EXPR _recursive_suffix_start "${_recursive_sep} + 4")
                string(SUBSTRING "${_pattern}" ${_recursive_suffix_start} -1 _recursive_suffix)
                file(GLOB_RECURSE _matches CONFIGURE_DEPENDS "${_recursive_root}/${_recursive_suffix}")
            else()
                file(GLOB _matches CONFIGURE_DEPENDS "${_pattern}")
            endif()

            if(_matches)
                list(SORT _matches)
                list(GET _matches 0 _found)
                break()
            endif()
        endif()
    endforeach()

    set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()
