/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112467-g5ddab49d48-20231017"
#endif /* AVUTIL_FFVERSION_H */
