function(detect_platform OUTPUT_VAR)
    if(BAAS_OCR_ANDROID_BUILD)
        set(${OUTPUT_VAR} "Android" PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(${OUTPUT_VAR} "Linux" PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        set(${OUTPUT_VAR} "Windows" PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
        set(${OUTPUT_VAR} "MacOS" PARENT_SCOPE)
    else()
        message(STATUS "Unknown OS: ${CMAKE_SYSTEM_NAME}")
    endif()
endfunction()


function(Android_NDK_check)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        if(DEFINED ANDROID_NDK_PATH)
            set(CMAKE_TOOLCHAIN_FILE "${ANDROID_NDK_PATH}/build/cmake/android.toolchain.cmake" CACHE STRING "")
        else()
            message(FATAL_ERROR "For Android Compilation please set ANDROID_NDK_PATH or CMAKE_TOOLCHAIN_FILE")
        endif()
    endif()
endfunction()